apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hmoon
spec:
  replicas: 3
  selector:
    matchLabels: # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - myapp
              topologyKey: topology.kubernetes.io/zone
        # podAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #   - labelSelector:
        #       matchExpressions:
        #       - key: app.kubernetes.io/name
        #         operator: In
        #         values:
        #         - myapp
        #     topologyKey: topology.kubernetes.io/zone
      containers:
        - image: hmoon630/sample-fastapi
          name: myapp
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 820m
              memory: 1000Mi
            requests:
              cpu: 820m
              memory: 1000Mi
      terminationGracePeriodSeconds: 60