apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hmoon
spec:
  replicas: 3
  selector:
    matchLabels: # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      # serviceAccountName: foo-myapp
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: "ScheduleAnyway" # "DoNotSchedule", "ScheduleAnyway"
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: myapp
      tolerations:
        - key: "Management"
          operator: "Equal"       # "Equal", "Exists"
          value: "Apps"           # operator가 "Equal"인 경우에만 사용합니다.
          effect: "NoSchedule"    # "NoSchedule", "PreferNoSchedule", "NoExecute"
      containers:
        - image: hmoon630/sample-fastapi
          name: myapp
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
          lifecycle:
            # postStart:
            #   exec:
            #     command: ["/bin/sh","-c","sleep 100"]
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
      terminationGracePeriodSeconds: 60